# Generated by Django 5.0.7 on 2024-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image",),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="image_url"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=255),
        ),
    ]
