# Generated by Django 5.0.7 on 2024-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0002_remove_product_image_product_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image_url",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
